require 'pusher'

USE_PUSHER = ENV['USE_PUSHER'] || false
puts "Pusher is on!" if USE_PUSHER

PUSHER_APP_ID = ENV["PUSHER_APP_ID"]
PUSHER_KEY = ENV["PUSHER_KEY"]
PUSHER_SECRET = ENV["PUSHER_SECRET"]
PUSHER_CLUSTER = ENV["PUSHER_CLUSTER"] || 'us2'
PUSHER_LOGGER = ENV["PUSHER_LOGGER"]
PUSHER_ENCRYPTED = ENV["PUSHER_ENCRYPTED"] || false

Pusher.app_id = ::PUSHER_APP_ID
Pusher.key = ::PUSHER_KEY
Pusher.secret = ::PUSHER_SECRET
Pusher.cluster = ::PUSHER_CLUSTER
Pusher.logger = ::PUSHER_LOGGER
Pusher.encrypted = ::PUSHER_ENCRYPTED
